#ifndef __dialogAlarmItemModify__
#define __dialogAlarmItemModify__

/**
@file
Subclass of GUI_dialogAlarmItemModify, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

/** Implementing GUI_dialogAlarmItemModify */
class dialogAlarmItemModify : public GUI_dialogAlarmItemModify
{
public:
	/** Constructor */
	dialogAlarmItemModify( wxWindow* parent );
};

#endif // __dialogAlarmItemModify__
